
# Studio access for tenant "@@TENANT_NAME@@" — generated by tenantctl.
@@STUDIO_DOMAIN@@ {
	header -server

	basic_auth {
		@@DASHBOARD_USERNAME@@ @@DASHBOARD_PASSWORD_HASH@@
	}

	reverse_proxy @@TENANT_NAME@@-studio:3000
}
