# API routes for tenant "@@TENANT_NAME@@" — generated by tenantctl.
# Path mapping mirrors the official Kong configuration
# (docker/volumes/api/kong.yml).
@@TENANT_DOMAIN@@ {
	header -server

	handle /graphql/v1 {
		rewrite * /rpc/graphql
		reverse_proxy @@TENANT_NAME@@-rest:3000
	}

	handle_path /auth/v1/* {
		reverse_proxy @@TENANT_NAME@@-auth:9999
	}

	handle_path /rest/v1/* {
		reverse_proxy @@TENANT_NAME@@-rest:3000
	}

	handle_path /realtime/v1/api/* {
		rewrite * /api{uri}
		reverse_proxy realtime-dev.@@TENANT_NAME@@-realtime:4000 {
			header_up Host {upstream_hostport}
		}
	}

	handle_path /realtime/v1/* {
		rewrite * /socket{uri}
		reverse_proxy realtime-dev.@@TENANT_NAME@@-realtime:4000 {
			header_up Host {upstream_hostport}
		}
	}

	handle_path /storage/v1/* {
		reverse_proxy @@TENANT_NAME@@-storage:5000
	}

	handle {
		respond "Not found" 404
	}
}
