# Environment for tenant "@@TENANT_NAME@@" — generated by tenantctl.
# This file contains secrets. Keep permissions at 600 and out of git.

TENANT_NAME=@@TENANT_NAME@@
TENANT_DOMAIN=@@TENANT_DOMAIN@@
STUDIO_DOMAIN=@@STUDIO_DOMAIN@@

# Optional services (comma-separated docker compose profiles:
# realtime, storage, studio)
COMPOSE_PROFILES=@@COMPOSE_PROFILES@@

# Resource caps (db container; other services have fixed caps in the
# compose file)
TENANT_DB_MEM_LIMIT=@@TENANT_DB_MEM_LIMIT@@
TENANT_DB_CPUS=@@TENANT_DB_CPUS@@

############
# Secrets — unique per tenant
############
POSTGRES_PASSWORD=@@POSTGRES_PASSWORD@@
JWT_SECRET=@@JWT_SECRET@@
ANON_KEY=@@ANON_KEY@@
SERVICE_ROLE_KEY=@@SERVICE_ROLE_KEY@@
SECRET_KEY_BASE=@@SECRET_KEY_BASE@@
PG_META_CRYPTO_KEY=@@PG_META_CRYPTO_KEY@@

# Studio basic-auth credentials (used by the Caddy route; share with the
# client only if they get Studio access)
DASHBOARD_USERNAME=@@DASHBOARD_USERNAME@@
DASHBOARD_PASSWORD=@@DASHBOARD_PASSWORD@@

############
# Database
############
POSTGRES_DB=postgres
POSTGRES_PORT=5432

############
# API / Auth
############
API_EXTERNAL_URL=https://@@TENANT_DOMAIN@@
# Set to the client's app URL once known (used in auth emails/redirects)
SITE_URL=https://@@TENANT_DOMAIN@@
ADDITIONAL_REDIRECT_URLS=
JWT_EXPIRY=3600
DISABLE_SIGNUP=false
ENABLE_EMAIL_SIGNUP=true
ENABLE_ANONYMOUS_USERS=false
# Auto-confirm is on by default so signup works before SMTP is configured.
# Turn it off once SMTP is set up.
ENABLE_EMAIL_AUTOCONFIRM=true
ENABLE_PHONE_SIGNUP=false
ENABLE_PHONE_AUTOCONFIRM=false

############
# SMTP — fill in to enable real auth emails
############
SMTP_ADMIN_EMAIL=
SMTP_HOST=
SMTP_PORT=587
SMTP_USER=
SMTP_PASS=
SMTP_SENDER_NAME=

############
# PostgREST
############
PGRST_DB_SCHEMAS=public,storage,graphql_public
PGRST_DB_MAX_ROWS=1000

############
# Storage
############
FILE_SIZE_LIMIT=52428800
